/* tabla login */

CREATE TABLE LOGIN (
ID_USUARIO VARCHAR2(20)CONSTRAINT LO_IDU_PK PRIMARY KEY,
CONTRASENIA VARCHAR2(50) CONSTRAINT LO_CON_NN NOT NULL,
TIPOLOGIN VARCHAR2(20) CONSTRAINT LO_TIPO_NN NOT NULL);

/* tabla director */

CREATE TABLE DIRECTOR (
DNI VARCHAR2 (9) CONSTRAINT DU_DNI_PK PRIMARY KEY,
NOMBRE VARCHAR2 (50) CONSTRAINT DU_NO_NN NOT NULL,
TELEFONO VARCHAR2 (15) CONSTRAINT DU_TEL_UK UNIQUE,
EMAIL VARCHAR2 (30) CONSTRAINT DU_EMAIL_UK UNIQUE);

/* TABLA EQUIPO */

CREATE TABLE EQUIPO (
ID_EQUIPO NUMBER (5) CONSTRAINT EQ_ID_PK PRIMARY KEY,
NOMBRE VARCHAR2(50) CONSTRAINT EQ_NOM_NN NOT NULL,
LOCALIDAD VARCHAR2(30) CONSTRAINT EQ_LOC_NOT NULL,
DNI_DIRECTOR VARCHAR2 (9) CONSTRAINT EQ_DNIDI_FK REFERENCES DIRECTOR(DNI)
ON DELETE CASCADE);


/*TABLA JUGADOR*/

CREATE TABLE JUGADOR (
DNI VARCHAR2(9) CONSTRAINT JU_DNI_PK PRIMARY KEY,
NOMBRE VARCHAR2(50) CONSTRAINT JU_NOM_NN NOT NULL,
NICKNAME VARCHAR2 (50) CONSTRAINT JU_NICK_UK UNIQUE,
SUELDO NUMBER(20,2) CONSTRAINT JU_sueldo_max CHECK (SUELDO<100000),
TELEFONO VARCHAR2 (15) CONSTRAINT JU_TEL_NN NOT NULL);

/* TABLA LIGA */


CREATE TABLE LIGA (
ID_LIGA NUMBER(5) CONSTRAINT LI_ID_PK PRIMARY KEY,
NOMBRE VARCHAR2(50) CONSTRAINT LI_NOM_NN NOT NULL,
FECHA_INICIO VARCHAR2(10) CONSTRAINT LI_FI_NN NOT NULL,
TERMINADO CHAR(1));


/* TABLA PUNTUACION */
CREATE TABLE PUNTUACION (
ID_EQUIPOPTS NUMBER(5) CONSTRAINT PUN_IDE_FK REFERENCES EQUIPO(ID_EQUIPO)
ON DELETE CASCADE,
ID_LIGAPTS NUMBER (5) CONSTRAINT PUN_IDL_FK REFERENCES LIGA(ID_LIGA)
ON DELETE CASCADE,
PUNTOS NUMBER(5) DEFAULT 0,
CONSTRAINT PUNT_PK PRIMARY KEY (ID_EQUIPOPTS, ID_LIGAPTS));

/* TABLA LOGIN */

CREATE TABLE LOGIN (
ID_USUARIO VARCHAR2(20)CONSTRAINT LO_IDU_PK PRIMARY KEY,
CONTRASENIA VARCHAR2(20) ,
TIPOLOGIN VARCHAR2(20) CONSTRAINT LO_TIPO_NN NOT NULL);


/* TABLA JUGADOR_EQUIPO */

CREATE TABLE JUGADOR_EQUIPO (
ID_JUGADOR_EQUIPO NUMBER(5) CONSTRAINT JUEQ_IDJE_PK PRIMARY KEY,
DNI_JUGADOR VARCHAR2(9) CONSTRAINT JUEQ_DJ_FK REFERENCES JUGADOR(DNI),
ID_EQUIPO NUMBER(5) CONSTRAINT JUEQ_IE_FK REFERENCES EQUIPO(ID_EQUIPO),
FECHA_ALTA VARCHAR2(10) CONSTRAINT JUEQ_FA_NN NOT NULL,
FECHA_BAJA VARCHAR2(10));

select max(id_jugador_equipo) from jugador_equipo;


/* JORNADA */

CREATE TABLE JORNADA(
ID_JORNADA NUMBER(5) CONSTRAINT JO_IDJ_PK PRIMARY KEY,
ID_LIGAENJORNADA NUMBER (5) CONSTRAINT JOR_IDL_FK REFERENCES LIGA(ID_LIGA)
ON DELETE CASCADE,
DIA NUMBER(2));

/* ENCUENTRO */

CREATE TABLE ENCUENTRO (
ID_ENCUENTRO NUMBER(5) CONSTRAINT EN_ID_PK PRIMARY KEY,
GANADOR NUMBER(1) CONSTRAINT EN_GANA_CK CHECK (GANADOR >=0 AND GANADOR <=3),
ID_EQUIPO1 NUMBER(5) CONSTRAINT EN_EQ1_FK REFERENCES EQUIPO(ID_EQUIPO)
ON DELETE SET NULL,
ID_EQUIPO2 NUMBER(5) CONSTRAINT EN_EQ2_FK REFERENCES EQUIPO(ID_EQUIPO)
ON DELETE SET NULL,
ID_LIGAEN NUMBER (5) CONSTRAINT EN_LIG_FK REFERENCES LIGA(ID_LIGA)
ON DELETE SET NULL,
ID_JORNADAEN NUMBER (5) CONSTRAINT EN_JOR_FK REFERENCES JORNADA(ID_JORNADA)
ON DELETE SET NULL);


/*PAQUETE DATOS JUGADOR */
CREATE OR REPLACE PACKAGE DATOS_JUGADOR AS

PROCEDURE INSERTAR_JUGADOR (PDNI IN JUGADOR.DNI%TYPE,
PNOMBRE IN JUGADOR.NOMBRE%TYPE,
PNICKNAME IN JUGADOR.NICKNAME%TYPE,
PSUELDO IN JUGADOR.SUELDO%TYPE,
PTELEFONO IN JUGADOR.TELEFONO%TYPE);

/*modificar salario*/
PROCEDURE MODIFICAR_SUELDO (PDNI IN JUGADOR.DNI%TYPE,
PSUELDO IN JUGADOR.SUELDO%TYPE);

/* MODIFICAR NICKNAME*/
PROCEDURE MODIFICAR_NICKNAME (PDNI IN JUGADOR.DNI%TYPE,
 PNICKNAME IN JUGADOR.NICKNAME%TYPE);
 
/* MODIFICAR TELEFONO*/
PROCEDURE MODIFICAR_TELEFONO (PDNI IN JUGADOR.DNI%TYPE,
PTELEFONO IN JUGADOR.TELEFONO%TYPE);

END DATOS_JUGADOR;

CREATE OR REPLACE PACKAGE BODY DATOS_JUGADOR IS

/*INSERTAR JUGADOR */

PROCEDURE INSERTAR_JUGADOR
(PDNI IN JUGADOR.DNI%TYPE,
PNOMBRE IN JUGADOR.NOMBRE%TYPE,
PNICKNAME IN JUGADOR.NICKNAME%TYPE,
PSUELDO IN JUGADOR.SUELDO%TYPE,
PTELEFONO IN JUGADOR.TELEFONO%TYPE)
IS
VDNII JUGADOR.DNI%TYPE;
BEGIN
SELECT DNI INTO VDNII
FROM JUGADOR
WHERE DNI = PDNI;

RAISE_APPLICATION_ERROR (-1002, 'El jugador ya existe');

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
        
INSERT INTO JUGADOR (DNI, NOMBRE, NICKNAME, SUELDO, TELEFONO)
VALUES ( PDNI, PNOMBRE, PNICKNAME, PSUELDO, PTELEFONO);
END;

/* MODIFICAR SALARIO JUGADOR */

PROCEDURE MODIFICAR_SUELDO
(PDNI IN JUGADOR.DNI%TYPE,
PSUELDO IN JUGADOR.SUELDO%TYPE)
IS
BEGIN
    UPDATE JUGADOR
    SET SUELDO = PSUELDO
    WHERE DNI = PDNI;
    
    IF SQL%NOTFOUND THEN 
        RAISE_APPLICATION_ERROR (-1001, 'El jugador no existe');
    END IF;
END;

/* MODIFICAR NICKNAME JUGADOR */
PROCEDURE MODIFICAR_NICKNAME
(PDNI IN JUGADOR.DNI%TYPE,
 PNICKNAME IN JUGADOR.NICKNAME%TYPE)
 IS 
 BEGIN
    UPDATE JUGADOR
    SET NICKNAME = PNICKNAME
    WHERE DNI = PDNI;
    
    IF SQL%NOTFOUND THEN
        RAISE_APPLICATION_ERROR (-1001, 'El jugador no existe');
    END IF;
END;

/* MODIFICAR TELEFONO JUGADOR */

PROCEDURE MODIFICAR_TELEFONO
(PDNI IN JUGADOR.DNI%TYPE,
PTELEFONO IN JUGADOR.TELEFONO%TYPE)
IS 
BEGIN 
    UPDATE JUGADOR
    SET TELEFONO = PTELEFONO
    WHERE DNI = PDNI;
    
    IF SQL%NOTFOUND THEN
        RAISE_APPLICATION_ERROR (-1001, ' El jugador no existe');
    END IF;
END;


END DATOS_JUGADOR;


/* PAQUETE DATOS DE DIRECTOR */

CREATE OR REPLACE PACKAGE DATOS_DIRECTOR AS


PROCEDURE INSERTAR_DIRECTOR (P_DNI IN DIRECTOR.DNI%TYPE,
P_NOMBRE IN DIRECTOR.NOMBRE%TYPE,
P_TELEFONO IN DIRECTOR.TELEFONO%TYPE,
P_EMAIL IN DIRECTOR.EMAIL%TYPE);

PROCEDURE MODIFICAR_TELEFONO (PDNI IN DIRECTOR.DNI%TYPE,
PTELEFONO IN DIRECTOR.TELEFONO%TYPE);

PROCEDURE MODIFICAR_EMAIL (PDNI IN DIRECTOR.DNI%TYPE,
PEMAIL IN DIRECTOR.EMAIL%TYPE);

PROCEDURE MODIFICAR_NOMBRE (PDNI IN DIRECTOR.DNI%TYPE,
PNOMBRE IN DIRECTOR.NOMBRE%TYPE);

END;


CREATE OR REPLACE PACKAGE BODY DATOS_DIRECTOR IS

/*INSERTAR+ JUGADOR*/

    PROCEDURE INSERTAR_DIRECTOR 
(P_DNI IN DIRECTOR.DNI%TYPE,
P_NOMBRE IN DIRECTOR.NOMBRE%TYPE,
P_TELEFONO IN DIRECTOR.TELEFONO%TYPE,
P_EMAIL IN DIRECTOR.EMAIL%TYPE)
IS
V_DNID DIRECTOR.DNI%TYPE;
BEGIN
    SELECT DNI INTO V_DNID
    FROM DIRECTOR
    WHERE DNI = V_DNID;
       
        EXCEPTION
            WHEN NO_DATA_FOUND THEN 
              RAISE_APPLICATION_ERROR (-2002, 'El director ya exite');
            
    INSERT INTO DIRECTOR (DNI, NOMBRE, TELEFONO, EMAIL)
    VALUES (P_DNI, P_NOMBRE, P_TELEFONO, P_EMAIL);
    END;

/*MODIFICAR TELEFONO*/

PROCEDURE MODIFICAR_TELEFONO
(PDNI IN DIRECTOR.DNI%TYPE,
PTELEFONO IN DIRECTOR.TELEFONO%TYPE)
IS 
BEGIN
        UPDATE DIRECTOR
    SET TELEFONO = PTELEFONO
    WHERE DNI = PDNI;
    
    IF SQL%NOTFOUND THEN
        RAISE_APPLICATION_ERROR ( -2001, ' El director no existe');
    END IF;    
END;

/* MODIFICAR EMAIL*/
PROCEDURE MODIFICAR_EMAIL
(PDNI IN DIRECTOR.DNI%TYPE,
PEMAIL IN DIRECTOR.EMAIL%TYPE)
IS
BEGIN
    UPDATE DIRECTOR
    SET EMAIL = PEMAIL
    WHERE DNI = PDNI;
    
     IF SQL%NOTFOUND THEN
        RAISE_APPLICATION_ERROR ( -2001, ' El director no existe');
    END IF;    
END;
/* MODIFICAR NOMBRE*/

PROCEDURE MODIFICAR_NOMBRE
(PDNI IN DIRECTOR.DNI%TYPE,
PNOMBRE IN DIRECTOR.NOMBRE%TYPE)
IS 
BEGIN
    UPDATE DIRECTOR
    SET NOMBRE = PNOMBRE
    WHERE DNI =PDNI;
    
     IF SQL%NOTFOUND THEN
        RAISE_APPLICATION_ERROR ( -2001, ' El director no existe');
    END IF;    
END;

END DATOS_DIRECTOR;

CREATE OR REPLACE PACKAGE DATOS_LIGA IS

PROCEDURE INSERTAR_LIGA (P_IDLIGA IN LIGA.ID_LIGA%TYPE,
P_NOMBRE IN LIGA.NOMBRE%TYPE,
P_FECHA_INICIO IN LIGA.FECHA_INICIO%TYPE,
P_TERMINADO IN LIGA.TERMINADO%TYPE);

PROCEDURE MODIFICAR_FECHAINICIO (P_IDLIGA IN LIGA.ID_LIGA%TYPE,
P_FECHA_INICIO IN LIGA.FECHA_INICIO%TYPE);

PROCEDURE MODIFICAR_TERMINADO ( P_IDLIGA IN LIGA.ID_LIGA%TYPE,
P_TERMINADO IN LIGA.TERMINADO%TYPE);
END;

CREATE OR REPLACE PACKAGE BODY DATOS_LIGA IS

/*INSERTAR LIGA*/

PROCEDURE INSERTAR_LIGA (P_IDLIGA IN LIGA.ID_LIGA%TYPE,
P_NOMBRE IN LIGA.NOMBRE%TYPE,
P_FECHA_INICIO IN LIGA.FECHA_INICIO%TYPE,
P_TERMINADO IN LIGA.TERMINADO%TYPE)
IS 
V_IDLIGA LIGA.ID_LIGA%TYPE;
BEGIN

SELECT ID_LIGA INTO V_IDLIGA
FROM LIGA
WHERE ID_LIGA = P_IDLIGA;

    
    
    EXCEPTION 
        WHEN NO_DATA_FOUND THEN
        
            RAISE_APPLICATION_ERROR (-5002, 'La Liga ya existe');
    
INSERT INTO LIGA ( ID_LIGA, NOMBRE, FECHA_INICIO, TERMINADO)
VALUES ( P_IDLIGA, P_NOMBRE, P_FECHA_INICIO,P_TERMINADO);
END;

/* MODIFICAR FECHA INICIO LIGA*/

PROCEDURE MODIFICAR_FECHAINICIO (P_IDLIGA IN LIGA.ID_LIGA%TYPE,
P_FECHA_INICIO IN LIGA.FECHA_INICIO%TYPE)
IS
V_IDLIGA LIGA.ID_LIGA%TYPE;
BEGIN

   UPDATE LIGA 
    SET FECHA_INICIO = P_FECHA_INICIO
    WHERE ID_LIGA =P_IDLIGA;

    IF SQL%NOTFOUND THEN

  RAISE_APPLICATION_ERROR (-5001, 'La liga no existe');
  
  END IF;
  
END;

/* MODIFICAR TERMINADO EN LIGA*/

PROCEDURE MODIFICAR_TERMINADO ( P_IDLIGA IN LIGA.ID_LIGA%TYPE,
P_TERMINADO IN LIGA.TERMINADO%TYPE)
IS
V_IDLIGA LIGA.ID_LIGA%TYPE;
BEGIN

  UPDATE LIGA
  SET TERMINADO = P_TERMINADO
  WHERE ID_LIGA = P_IDLIGA;
  
  IF SQL%NOTFOUND THEN
  
    RAISE_APPLICATION_ERROR (-5001, 'La liga no existe');
    
  END IF;  

  
END;

END;

/* DATOS DE EQUIPOS */

CREATE OR REPLACE PACKAGE DATOS_EQUIPO IS

PROCEDURE INSERTAR_EQUIPO (P_IDEQUIPO IN EQUIPO.ID_EQUIPO%TYPE,
P_NOMBRE IN EQUIPO.NOMBRE%TYPE,
P_LOCALIDAD IN EQUIPO.LOCALIDAD%TYPE,
P_DNIDIRECTOR IN EQUIPO.DNI_DIRECTOR%TYPE);

PROCEDURE MODIFICAR_DIRECTOR (P_IDEQUIPO IN EQUIPO.ID_EQUIPO%TYPE,
P_DNIDIRECTOR IN EQUIPO.DNI_DIRECTOR%TYPE);

PROCEDURE MODIFICAR_LOCALIDAD (P_IDEQUIPO IN EQUIPO.ID_EQUIPO%TYPE,
P_LOCALIDAD IN EQUIPO.LOCALIDAD%TYPE);

PROCEDURE MODIFICAR_NOMBRE (P_IDEQUIPO IN EQUIPO.ID_EQUIPO%TYPE,
P_NOMBRE IN EQUIPO.NOMBRE%TYPE);

END;


CREATE OR REPLACE PACKAGE BODY DATOS_EQUIPO IS

/* INSERTAR EQUIPO*/

    PROCEDURE INSERTAR_EQUIPO (P_IDEQUIPO IN EQUIPO.ID_EQUIPO%TYPE,
    P_NOMBRE IN EQUIPO.NOMBRE%TYPE,
    P_LOCALIDAD IN EQUIPO.LOCALIDAD%TYPE,
    P_DNIDIRECTOR IN EQUIPO.DNI_DIRECTOR%TYPE)
    IS
    V_IDEQUIPO EQUIPO.ID_EQUIPO%TYPE;
    V_DNIDIRECTOR EQUIPO.DNI_DIRECTOR%TYPE;
    BEGIN
    
    SELECT e.ID_EQUIPO, D.DNI  INTO V_IDEQUIPO,V_DNIDIRECTOR
    FROM EQUIPO E, DIRECTOR D
    WHERE ID_EQUIPO = P_IDEQUIPO AND D.DNI = E.DNI_DIRECTOR AND E.DNI_DIRECTOR = P_DNIDIRECTOR;
    
        RAISE_APPLICATION_ERROR (-3002, ' El equipo o el director no son correctos');
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
      
         INSERT INTO EQUIPO ( ID_EQUIPO, NOMBRE, LOCALIDAD, DNI_DIRECTOR)
    VALUES ( P_IDEQUIPO, P_NOMBRE, P_LOCALIDAD, P_DNIDIRECTOR);
      
           END;
    
PROCEDURE MODIFICAR_DIRECTOR (P_IDEQUIPO IN EQUIPO.ID_EQUIPO%TYPE,
P_DNIDIRECTOR IN EQUIPO.DNI_DIRECTOR%TYPE)
IS
V_DNIDIRECTOR EQUIPO.DNI_DIRECTOR%TYPE;
V_IDEQUIPO EQUIPO.ID_EQUIPO%TYPE;
BEGIN

   SELECT DNI INTO V_DNIDIRECTOR
    FROM DIRECTOR
    WHERE DNI = P_DNIDIRECTOR;
    
     UPDATE EQUIPO
    SET DNI_DIRECTOR = P_DNIDIRECTOR
    WHERE ID_EQUIPO = P_IDEQUIPO;
    
    IF SQL%NOTFOUND THEN
        RAISE_APPLICATION_ERROR (-3001, ' El equipo ya existe');
    END IF;    
    
      EXCEPTION
   WHEN NO_DATA_FOUND THEN
   
        RAISE_APPLICATION_ERROR (-2001, 'El director no existe');
        
        
   END;

PROCEDURE MODIFICAR_LOCALIDAD (P_IDEQUIPO IN EQUIPO.ID_EQUIPO%TYPE,
P_LOCALIDAD IN EQUIPO.LOCALIDAD%TYPE)
IS
V_IDEQUIPO EQUIPO.ID_EQUIPO%TYPE;
BEGIN
 
    UPDATE EQUIPO
    SET LOCALIDAD = P_LOCALIDAD
    WHERE ID_EQUIPO = P_IDEQUIPO;
    
        IF SQL%NOTFOUND THEN
        RAISE_APPLICATION_ERROR (-3001,'El equpo no existe');
        END IF;
      
END;

PROCEDURE MODIFICAR_NOMBRE (P_IDEQUIPO IN EQUIPO.ID_EQUIPO%TYPE,
P_NOMBRE IN EQUIPO.NOMBRE%TYPE)
IS
V_IDEQUIPO EQUIPO.ID_EQUIPO%TYPE;
BEGIN 

    UPDATE EQUIPO
    SET NOMBRE = P_NOMBRE
    WHERE ID_EQUIPO = P_IDEQUIPO;
    
        IF SQL%NOTFOUND THEN
        RAISE_APPLICATION_ERROR (-3001,'El equpo no existe');
        END IF;
  
    END;
END;

/* EQUIPOS*/

CREATE OR REPLACE PACKAGE EQUIPOS IS

PROCEDURE INSERTAR_JUGADORAEQUIPO ( P_DNIJUGADOR IN JUGADOR_EQUIPO.DNI_JUGADOR%TYPE,
P_FECHAALTA IN JUGADOR_EQUIPO.FECHA_ALTA%TYPE,
P_IDEQUIPO IN JUGADOR_EQUIPO.ID_EQUIPO%TYPE);

PROCEDURE QUITAR_JUGADORDEEQUIPO (P_DNIJUGADOR IN JUGADOR_EQUIPO.DNI_JUGADOR%TYPE,
P_IDEQUIPO IN JUGADOR_EQUIPO.ID_EQUIPO%TYPE,
P_FECHABAJA IN JUGADOR_EQUIPO.FECHA_BAJA%TYPE);

END;

CREATE OR REPLACE PACKAGE BODY EQUIPOS IS

/* INSERTAR JUGADOR A EQUIPO*/

        PROCEDURE INSERTAR_JUGADORAEQUIPO ( P_DNIJUGADOR IN JUGADOR_EQUIPO.DNI_JUGADOR%TYPE,
        P_FECHAALTA IN JUGADOR_EQUIPO.FECHA_ALTA%TYPE,
        P_IDEQUIPO IN JUGADOR_EQUIPO.ID_EQUIPO%TYPE)
        IS
        V_DNIJUGADOR JUGADOR_EQUIPO.DNI_JUGADOR%TYPE;
        V_DNI JUGADOR.DNI%TYPE;
        V_IDEQUIPO JUGADOR_EQUIPO.ID_EQUIPO%TYPE;
        V_FECHABAJA JUGADOR_EQUIPO.FECHA_BAJA%TYPE;
      
        BEGIN
        
        SELECT DNI_JUGADOR INTO V_DNIJUGADOR
        FROM JUGADOR_EQUIPO
        WHERE DNI_JUGADOR = P_DNIJUGADOR AND FECHA_BAJA IS NULL;
        
        
        SELECT DNI INTO V_DNI
        FROM JUGADOR
        WHERE DNI = P_DNIJUGADOR;
        
        INSERT INTO JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO, DNI_JUGADOR, ID_EQUIPO, FECHA_ALTA)
        VALUES (MASUNO.nextval , P_DNIJUGADOR, P_IDEQUIPO, P_FECHAALTA);
        
   
        EXCEPTION
        
                WHEN NO_DATA_FOUND THEN
        
             RAISE_APPLICATION_ERROR(-1003,'El jugador ya esta en otro equipo o no existe');
        
        END ;
        
        /* QUITAR JUGADOR DE EQUIPO*/
        
PROCEDURE QUITAR_JUGADORDEEQUIPO (P_DNIJUGADOR IN JUGADOR_EQUIPO.DNI_JUGADOR%TYPE,
P_IDEQUIPO IN JUGADOR_EQUIPO.ID_EQUIPO%TYPE,
P_FECHABAJA IN JUGADOR_EQUIPO.FECHA_BAJA%TYPE)
IS 
V_JUGADOR NUMBER;
V_FECHABAJA NUMBER;
BEGIN

UPDATE JUGADOR_EQUIPO
SET FECHA_BAJA = P_FECHABAJA
WHERE DNI_JUGADOR = P_DNIJUGADOR AND FECHA_BAJA IS NULL;

    IF SQL%NOTFOUND THEN

        RAISE_APPLICATION_ERROR (-8523, 'El jugador no se encuentra en ningun equipo');

    END IF;

END ;

END EQUIPOS;

/* PUNTUACION*/

CREATE OR REPLACE PACKAGE DATOS_PUNTUACION IS
    PROCEDURE INSERTAR_EQUIPOALIGA ( P_IDEQUIPOPTS IN PUNTUACION.ID_EQUIPOPTS%TYPE,
    P_IDLIGAPTS IN PUNTUACION.ID_LIGAPTS%TYPE);
    
    PROCEDURE CAMBIAR_PUNTOS ( P_IDEQUIPOPTS IN PUNTUACION.ID_EQUIPOPTS%TYPE,
    P_IDLIGAPTS IN PUNTUACION.ID_LIGAPTS%TYPE,
    P_PTOS IN PUNTUACION.PUNTOS%TYPE);
    
    END;
    
CREATE OR REPLACE PACKAGE BODY DATOS_PUNTUACION IS

    /* INSERTAR EQUIPO A LIGA*/
    
     PROCEDURE INSERTAR_EQUIPOALIGA ( P_IDEQUIPOPTS IN PUNTUACION.ID_EQUIPOPTS%TYPE,
    P_IDLIGAPTS IN PUNTUACION.ID_LIGAPTS%TYPE)
    IS
    V_IDEQUIPO NUMBER;
    V_IDEQUIPO2 NUMBER;
    V_IDLIGA NUMBER;
    BEGIN
    

    SELECT ID_LIGA INTO V_IDLIGA
    FROM LIGA
    WHERE ID_LIGA = P_IDLIGAPTS;

    
    SELECT ID_EQUIPO INTO V_IDEQUIPO
    FROM EQUIPO
    WHERE ID_EQUIPO = P_IDEQUIPOPTS;
    
    INSERT INTO PUNTUACION (ID_EQUIPOPTS, ID_LIGAPTS)
    VALUES (P_IDEQUIPOPTS, P_IDLIGAPTS);
    
        EXCEPTION   
            WHEN NO_DATA_FOUND THEN
    
     RAISE_APPLICATION_ERROR (-5003, 'El equipo o la liga no existen');
    
    END;
    
    PROCEDURE CAMBIAR_PUNTOS ( P_IDEQUIPOPTS IN PUNTUACION.ID_EQUIPOPTS%TYPE,
    P_IDLIGAPTS IN PUNTUACION.ID_LIGAPTS%TYPE,
    P_PTOS IN PUNTUACION.PUNTOS%TYPE)
    IS 
    V_IDEQUIPO NUMBER;
    V_IDLIGA NUMBER;
    BEGIN
    
        UPDATE PUNTUACION
    SET PUNTOS =P_PTOS
    WHERE ID_EQUIPOPTS = P_IDEQUIPOPTS AND ID_LIGAPTS = P_IDLIGAPTS;
    
    IF SQL%NOTFOUND THEN
    
    RAISE_APPLICATION_ERROR ( -88521, 'La liga o el equipo no son correctos');
    
    END IF;
    

    
    END;
    END DATOS_PUNTUACION;
    
    /* PARA ENCUENTRO */
    
    /* PAQUETE ENCUENTRO */
    
    CREATE OR REPLACE PACKAGE DATOS_ENCUENTRO IS
    PROCEDURE AÑADIR_ENCUENTRO ( P_IDEQUIPO1 IN ENCUENTRO.ID_EQUIPO1%TYPE,
    P_IDEQUIPO2 IN ENCUENTRO.ID_EQUIPO2%TYPE,
    P_IDLIGAEN IN ENCUENTRO.ID_LIGAEN%TYPE,
    P_IDJORNADA IN ENCUENTRO.ID_JORNADAEN%TYPE,
    P_IDENCUENTRO IN ENCUENTRO.ID_ENCUENTRO%TYPE);
    
    PROCEDURE MODIFICAR_GANADOR ( P_GANADOR IN ENCUENTRO.GANADOR%TYPE,
    P_IDENCUENTRO IN ENCUENTRO.ID_ENCUENTRO%TYPE);
        
    END;
    
    CREATE OR REPLACE PACKAGE BODY DATOS_ENCUENTRO IS
    
    PROCEDURE AÑADIR_ENCUENTRO ( P_IDEQUIPO1 IN ENCUENTRO.ID_EQUIPO1%TYPE,
    P_IDEQUIPO2 IN ENCUENTRO.ID_EQUIPO2%TYPE,
    P_IDLIGAEN IN ENCUENTRO.ID_LIGAEN%TYPE,
    P_IDJORNADA IN ENCUENTRO.ID_JORNADAEN%TYPE,
    P_IDENCUENTRO IN ENCUENTRO.ID_ENCUENTRO%TYPE)
    IS
    V_EQUIPO1 NUMBER;
    V_EQUIPO2 NUMBER;
    V_LIGA NUMBER;
    V_LIGA2 NUMBER;
    V_LIGA3 NUMBER;
    V_JORNADA NUMBER;
    BEGIN
    
    SELECT ID_LIGA INTO V_LIGA
    FROM LIGA
    WHERE ID_LIGA = P_IDLIGAEN;

      
    SELECT ID_EQUIPOPTS, ID_LIGAPTS INTO V_EQUIPO1, V_LIGA2
    FROM PUNTUACION
    WHERE ID_EQUIPOPTS = P_IDEQUIPO1 AND ID_LIGAPTS = P_IDLIGAEN;
    
    
    SELECT ID_EQUIPOPTS, ID_LIGAPTS INTO V_EQUIPO2, V_LIGA3
    FROM PUNTUACION
    WHERE ID_EQUIPOPTS = P_IDEQUIPO2 AND ID_LIGAPTS = P_IDLIGAEN;
       
    
    INSERT INTO ENCUENTRO (ID_ENCUENTRO ,ID_EQUIPO1, ID_EQUIPO2, ID_LIGAEN, ID_JORNADAEN)
    VALUES(P_IDENCUENTRO, P_IDEQUIPO1, P_IDEQUIPO2, P_IDLIGAEN,P_IDJORNADA);
    
     EXCEPTION   
            WHEN NO_DATA_FOUND THEN 
            
                RAISE_APPLICATION_ERROR (-5003, ' El equipo o la liga no existen');
    
    END;
    
    PROCEDURE MODIFICAR_GANADOR ( P_GANADOR IN ENCUENTRO.GANADOR%TYPE,
    P_IDENCUENTRO IN ENCUENTRO.ID_ENCUENTRO%TYPE)
    IS
    V_IDENCUENTRO NUMBER;
    BEGIN
     
    UPDATE ENCUENTRO
    SET GANADOR = P_GANADOR
    WHERE ID_ENCUENTRO = P_IDENCUENTRO;
    
    IF SQL%NOTFOUND THEN
    
    RAISE_APPLICATION_ERROR (-6001, 'El encuentro no existe');
    
    END IF;
    END;
    
    END;
    
    
/* SECUENCIA*/
CREATE SEQUENCE MASUNO
INCREMENT BY 1
START WITH 1
NOCYCLE;


/* TRIGGER <6 MIEMBROS EQUIPO */

CREATE OR REPLACE TRIGGER JUGADOR_EQUIPO_IB BEFORE
INSERT ON JUGADOR_EQUIPO FOR EACH ROW
DECLARE 
V_EQUIPONUM NUMBER(5);
BEGIN
SELECT COUNT(ID_EQUIPO) INTO V_EQUIPONUM
FROM JUGADOR_EQUIPO
WHERE ID_EQUIPO= (:NEW.ID_EQUIPO) AND FECHA_BAJA IS NULL;
IF V_EQUIPONUM >5 THEN 
RAISE_APPLICATION_ERROR(-3003,'El equipo esta completo');
END IF;
END;

/* TRIGGER SALARIO TOTAL DE UN EQUIPO INFERIOR A 200000*/

CREATE OR REPLACE TRIGGER jugador_EQUIPO_SB BEFORE
INSERT OR UPDATE ON JUGADOR_EQUIPO FOR EACH ROW
DECLARE 
T_EQSALTO NUMBER;
T_SALARIONU NUMBER;
BEGIN
SELECT SUM(c.SUELDO) INTO T_EQSALTO
FROM JUGADOR C , JUGADOR_EQUIPO E
WHERE E.ID_EQUIPO = (:NEW.ID_EQUIPO) and C.DNI = E.DNI_JUGADOR;
SELECT SUELDO INTO T_SALARIONU
FROM JUGADOR C, JUGADOR_EQUIPO E
WHERE C.DNI = :NEW.DNI_JUGADOR;
IF (T_EQSALTO+ T_SALARIONU) > 200000 THEN
RAISE_APPLICATION_ERROR(-8002,'Supera el salario permitido');
end if;
END;

drop trigger jugador_equipo_sb;

/*TRIGGER SALARIO MINIMO*/

CREATE OR REPLACE TRIGGER JUGADOR_IB BEFORE
INSERT OR UPDATE ON JUGADOR FOR EACH ROW
BEGIN
    IF (:NEW.SUELDO < 8830.80) THEN
        RAISE_APPLICATION_ERROR(-8001,'SALARIO NO VALIDO');
    END IF;
END;

  /* INSERCION EN LIGA */

CREATE OR REPLACE TRIGGER INSERCION_LIGA BEFORE
INSERT OR UPDATE ON PUNTUACION FOR EACH ROW
DECLARE 
T_EQUIPO NUMBER;
BEGIN    
 SELECT COUNT(*) INTO T_EQUIPO
 FROM JUGADOR_EQUIPO
 WHERE ID_EQUIPO = (:NEW.ID_EQUIPOPTS) AND FECHA_BAJA IS NULL;
 
    IF T_EQUIPO < 2 THEN
    RAISE_APPLICATION_ERROR (-3004, 'El equipo no tiene los jugadores necesarios para acceder a la liga');
    END IF;
    
END INSERCION_LIGA;